### ISSUE TITLE
As a developer I need to make sure the project completes the checklist of release criterias

### ISSUE THREAD

**Issue by EllaMiri** [EllaMiri/ClimaxMusicEmpire#23]
Checklista för release

Bekräfta att allt fungerar för lanseringen av din webbplats / mobilapp enligt checklistan nedan. 

Observera: 1) Inga dokument behöver lämnas in och 2) tillämpa endast relevanta delar.

1. Lansering:

- [x] Lägg till en Fav.icon.
- [x] Använd https (SSL)
Gratis med [Let’s Encrypt SSL certifikat](https://letsencrypt.org/sv/).
- [x] Bekräfta att 404 sidan visas (kan vara enklare).
- [x] Alla länkar på webbplatsen fungerar. Testa olika navigationsflöden.
- [x] Tag bort “dummy” innehåll om du använder ett CMS som tex WordPress
Till exempel Hello World post om den existerar.
- [x] Startsidan visar tydligt vad syftet med webbplatsen är och vad för typ av sajt det är. 
Klarar du 5 sekunders testet?

2. Bilder och grafik
- [x] Alla bilder är tydliga.
För webbutik gäller det både produktsidan och kategorisidan.
- [x] Bilder har alt image taggar.
- [x] Om möjligt, sätt en lång expiry period för statiska resurser som bilder.

3. Struktur
- [x] Bekräfta att sidorna har H1 taggar (rubriker)
- [x] Även H2 och H3 om du använder underrubriker.
- [x] Bekräfta att titeln (dvs page title, sidtitel) är relevant och unik för varje sida.
- [x] Bekräfta att robots.txt fil existerar. 
- [x] Uteslut vissa sidor som du inte vill att sökmotorer ska indexera genom att använda disallow.

4. Responsivitet
- [x] Testa att webbplatsen visas väl i både mobil och tablet vy. Du kan testa i webbläsarens utvecklingsverktyg. Till exempel, i Chrome developer.
- [x] Testa navigering från startsida till olika sidor.
- [x] Testa eventuell sortering och filtrering.
- [x] Försäkra dig om att det inte finns errors i console.

Acceptance criterias:

- [x] Allt är ifyllt och dubbekollat
